services:
  - type: web
    name: fiscalizaplus
    env: node
    rootDir: codigo
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

